### ISSUE TITLE
granularity is always zero

### ISSUE THREAD

**Issue by Jmalinza** [ajcalderont/gmai#1]
in `get_alloc_info.cu` lines 44-59

    // Maximum allocations and granularity
    /*----------------------------------------------------------------------------------------*/
    char **h_data_array = (char**) malloc(pool_size * sizeof(char*));
    cudaHostAlloc((void**)&h_data_array[0], 1, cudaHostAllocMapped);
    break_02: __attribute__((unused));
    int granularity = 0, iteration = 0, flag = 0;
    while(!flag && iteration < pool_size)
    {
        iteration++; 
        cudaHostAlloc((void**)&h_data_array[iteration], 1, cudaHostAllocMapped);
    }
    for(int i = 0; i <= iteration; i++)
    {
        cudaFreeHost(h_data_array[i]);
    }
    free(h_data_array);

granularity is never incremented, resulting in divide by zero errors.

**Comment by ajcalderont** [comment]
The granularity variable is not meant to be incremented in `get_alloc_info.cu`, it is calculated in the background by the debugger script `.gdbinit`
```
# Granularity extraction
break get_alloc_info.cu:main:break_02
continue
break mmap
continue
set logging on
set variable main::granularity = main::pool_size/main::iteration
printf "GRN %d\n", main::granularity
set logging off
set variable main::flag = 1
delete
```
Try running `make clean_info` and then `make show_alloc_info arch=sm_53` (or using your architecture instead of sm_53) to get the allocator info
